d_terreros_final_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("weather4u.urls")),
    path('admin/', admin.site.urls),
]

weather4u/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'weather4u'

urlpatterns = [
    path("", views.home, name="index"),
    path("weather/", views.weather, name="weather"),
    path('five-day/', views.five_day, name='five_day'),
    path("what-to-wear/", views.what_to_wear, name="what_to_wear"),

    path("what-to-do/", views.what_to_do, name="what_to_do"),
    path("register/", views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(
        template_name="weather4u/login.html",
        redirect_authenticated_user=True,
        next_page='weather4u:index'
    ), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="weather4u:index"), name="logout"),
    path("profile/", views.profile, name="profile"),
]

templates/base.html
<!DOCTYPE html>
<html data-theme="fantasy" lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>{% block title %}Weather4u{% endblock %}</title>
    {% load static %}
    <link href="{% static 'css/output.css' %}" rel="stylesheet"/>
    <link id="dynamic-favicon" rel="icon" type="image/png" href="{% static 'default-icon.png' %}">

</head>
<body>
<div class="container mx-auto">
    <div class="navbar bg-base-100 shadow-sm">
        <div class="flex-none">
            <button class="btn btn-square btn-ghost">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                     class="inline-block h-5 w-5 stroke-current">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                          d="M4 6h16M4 12h16M4 18h16"></path>
                </svg>
            </button>
            <a href="{% url 'weather4u:index' %}" class="btn btn-ghost text-xl">Home</a>
        </div>
        <div class="flex-1">

        </div>
        <div class="flex-none">
            {% if user.is_authenticated %}
                <span class="text-sm mr-4">Welcome, {{ user.username }}!</span>
                <a href="{% url 'weather4u:profile' %}" class="btn btn-link">Profile</a>
                <form method="POST" action="{% url 'weather4u:logout' %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Logout</button>
                </form>
            {% else %}
                <a href="{% url 'weather4u:login' %}">Login</a>
                <a href="{% url 'weather4u:register' %}">Register</a>
            {% endif %}
        </div>
    </div>

    {% block content %}
        <!-- Child templates will inject here -->
    {% endblock %}
    <footer class="footer aligned-center sm:footer-horizontal bg-neutral text-neutral-content p-10">
        <nav>
            <h6 class="footer-title">Services</h6>
            <a href="{% url 'weather4u:five_day' %}" class="link link-hover">Weather</a>
        </nav>
        <nav>
            <h6 class="footer-title">Company</h6>
            <a class="link link-hover">About us</a>
        </nav>
        <nav>
            <h6 class="footer-title">Legal</h6>
            <a class="link link-hover">Terms of use</a>
        </nav>
    </footer>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const favicon = document.getElementById("dynamic-favicon");
        const weatherIconCode = "{{ result.icon|default:'' }}";

        {% if result and result.icon %}
        favicon.href = "https://openweathermap.org/img/wn/{{ result.icon }}.png";
        {% endif %}
    });
</script>
</body>
</html>